networks:
  default:
    external: true
    name: kafka-local

volumes:
  ct0: {}
  bk1: {}
  bk2: {}
  bk3: {}
  bk4: {}
  sr_secrets: {}
  c_kafka_data: {}
  c_kafka_secrets: {}

services:

  controller-0:
    image: confluentinc/cp-kafka:${VERSION}
    hostname: controller-0
    container_name: dk-controller-0
    stop_grace_period: 60s
    healthcheck:
      test: nc -z localhost 9091 || exit 1
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 3
    volumes:
      - ct0:/var/lib/kafka/data
      - ./jmx:/opt/jmx_prometheus
      - ./secrets:/etc/kafka/secrets
    environment:
      CLUSTER_ID: "0000000000000000000000"
      KAFKA_LISTENERS: CONTROLLER://:9091
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:SASL_PLAINTEXT,INTERNAL:SASL_PLAINTEXT
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_PROCESS_ROLES: controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 10@controller-0:9091
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 4
      KAFKA_NODE_ID: 10
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OPTS: >-
        -Djava.security.auth.login.config=/etc/kafka/secrets/broker_jaas.conf
        -javaagent:/opt/jmx_prometheus/jmx_prometheus_javaagent.jar=7071:/opt/jmx_prometheus/kafka-config.yml
        -javaagent:/opt/jmx_prometheus/jolokia-jvm.jar=port=7072,host=*
      CONFLUENT_METRICS_ENABLE: "false"
      KAFKA_SSL_KEYSTORE_FILENAME: controller-0.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: kafka.key
      KAFKA_SSL_KEY_CREDENTIALS: kafka.key
      KAFKA_SSL_CLIENT_AUTH: none
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: kafka.key
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.server.truststore.jks
      KAFKA_AUTHORIZER_CLASS_NAME: org.apache.kafka.metadata.authorizer.StandardAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "false"
      KAFKA_SUPER_USERS: User:kafka-admin;User:kafka-broker;User:kafka-broker-v2
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN,SCRAM-SHA-512
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL: PLAIN

  broker-1:
    image: confluentinc/cp-kafka:${VERSION}
    hostname: broker-1
    container_name: dk-broker-1
    stop_grace_period: 60s
    healthcheck:
      test: nc -z localhost 9092 || exit 1
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 3
    depends_on:
      controller-0:
        condition: service_healthy
    ports:
      - "19092:19092"
      - "19093:19093"
      - "9092:19092"
      - "9093:19093"
    volumes:
      - bk1:/var/lib/kafka/data
      - ./jmx:/opt/jmx_prometheus
      - ./secrets:/etc/kafka/secrets
    environment:
      CLUSTER_ID: "0000000000000000000000"
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:SASL_PLAINTEXT,INTERNAL:SASL_PLAINTEXT,INTERNAL_SSL:SASL_SSL,HOST:SASL_PLAINTEXT,HOST_SSL:SASL_SSL
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker-1:9092,INTERNAL_SSL://broker-1:9093,HOST://localhost:19092,HOST_SSL://localhost:19093
      KAFKA_CONTROLLER_QUORUM_VOTERS: 10@controller-0:9091
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_NUM_PARTITIONS: 4
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 500
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_METRIC_REPORTERS:
      KAFKA_OPTS: >-
        -Djava.security.auth.login.config=/etc/kafka/secrets/broker_jaas.conf
        -javaagent:/opt/jmx_prometheus/jmx_prometheus_javaagent.jar=7071:/opt/jmx_prometheus/kafka-config.yml
        -javaagent:/opt/jmx_prometheus/jolokia-jvm.jar=port=7072,host=*
      CONFLUENT_METRICS_ENABLE: "false"
      KAFKA_SSL_KEYSTORE_FILENAME: broker-1.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: kafka.key
      KAFKA_SSL_KEY_CREDENTIALS: kafka.key
      KAFKA_SSL_CLIENT_AUTH: none
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: kafka.key
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.server.truststore.jks
      KAFKA_AUTHORIZER_CLASS_NAME: org.apache.kafka.metadata.authorizer.StandardAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "false"
      KAFKA_SUPER_USERS: User:kafka-admin;User:kafka-broker;User:kafka-broker-v2
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN,SCRAM-SHA-512
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL: PLAIN

  broker-2:
    image: confluentinc/cp-kafka:${VERSION}
    hostname: broker-2
    container_name: dk-broker-2
    stop_grace_period: 60s
    healthcheck:
      test: nc -z localhost 9092 || exit 1
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 3
    depends_on:
      controller-0:
        condition: service_healthy
    ports:
      - "29092:29092"
      - "29093:29093"
    volumes:
      - bk2:/var/lib/kafka/data
      - ./jmx:/opt/jmx_prometheus
      - ./secrets:/etc/kafka/secrets
    environment:
      CLUSTER_ID: "0000000000000000000000"
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:SASL_PLAINTEXT,INTERNAL:SASL_PLAINTEXT,INTERNAL_SSL:SASL_SSL,HOST:SASL_PLAINTEXT,HOST_SSL:SASL_SSL
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker-2:9092,INTERNAL_SSL://broker-2:9093,HOST://localhost:29092,HOST_SSL://localhost:29093
      KAFKA_CONTROLLER_QUORUM_VOTERS: 10@controller-0:9091
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_NUM_PARTITIONS: 4
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 500
      KAFKA_METRIC_REPORTERS:
      KAFKA_OPTS: >-
        -Djava.security.auth.login.config=/etc/kafka/secrets/broker_jaas.conf
        -javaagent:/opt/jmx_prometheus/jmx_prometheus_javaagent.jar=7071:/opt/jmx_prometheus/kafka-config.yml
        -javaagent:/opt/jmx_prometheus/jolokia-jvm.jar=port=7072,host=*
      CONFLUENT_METRICS_ENABLE: "false"
      KAFKA_SSL_KEYSTORE_FILENAME: broker-2.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: kafka.key
      KAFKA_SSL_KEY_CREDENTIALS: kafka.key
      KAFKA_SSL_CLIENT_AUTH: none
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: kafka.key
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.server.truststore.jks
      KAFKA_AUTHORIZER_CLASS_NAME: org.apache.kafka.metadata.authorizer.StandardAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "false"
      KAFKA_SUPER_USERS: User:kafka-admin;User:kafka-broker;User:kafka-broker-v2
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN,SCRAM-SHA-512
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL: PLAIN

  broker-3:
    image: confluentinc/cp-kafka:${VERSION}
    hostname: broker-3
    container_name: dk-broker-3
    stop_grace_period: 60s
    healthcheck:
      test: nc -z localhost 9092 || exit 1
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 3
    depends_on:
      controller-0:
        condition: service_healthy
    ports:
      - "39092:39092"
      - "39093:39093"
    volumes:
      - bk3:/var/lib/kafka/data
      - ./jmx:/opt/jmx_prometheus
      - ./secrets:/etc/kafka/secrets
    environment:
      CLUSTER_ID: "0000000000000000000000"
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: broker
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:SASL_PLAINTEXT,INTERNAL:SASL_PLAINTEXT,INTERNAL_SSL:SASL_SSL,HOST:SASL_PLAINTEXT,HOST_SSL:SASL_SSL
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker-3:9092,INTERNAL_SSL://broker-3:9093,HOST://localhost:39092,HOST_SSL://localhost:39093
      KAFKA_CONTROLLER_QUORUM_VOTERS: 10@controller-0:9091
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_NUM_PARTITIONS: 4
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 500
      KAFKA_METRIC_REPORTERS:
      KAFKA_OPTS: >-
        -Djava.security.auth.login.config=/etc/kafka/secrets/broker_jaas.conf
        -javaagent:/opt/jmx_prometheus/jmx_prometheus_javaagent.jar=7071:/opt/jmx_prometheus/kafka-config.yml
        -javaagent:/opt/jmx_prometheus/jolokia-jvm.jar=port=7072,host=*
      CONFLUENT_METRICS_ENABLE: "false"
      KAFKA_SSL_KEYSTORE_FILENAME: broker-3.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: kafka.key
      KAFKA_SSL_KEY_CREDENTIALS: kafka.key
      KAFKA_SSL_CLIENT_AUTH: none
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: kafka.key
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.server.truststore.jks
      KAFKA_AUTHORIZER_CLASS_NAME: org.apache.kafka.metadata.authorizer.StandardAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "false"
      KAFKA_SUPER_USERS: User:kafka-admin;User:kafka-broker;User:kafka-broker-v2
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN,SCRAM-SHA-512
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL: PLAIN

#  broker-4:
#    image: confluentinc/cp-kafka:${VERSION}
#    hostname: dk-broker-4
#    container_name: dk-broker-4
#    stop_grace_period: 60s
#    healthcheck:
#      test: nc -z localhost 9092 || exit 1
#      start_period: 5s
#      interval: 5s
#      timeout: 5s
#      retries: 3
#    depends_on:
#      controller-0:
#        condition: service_healthy
#    ports:
#      - "49092:49092"
#      - "49093:49093"
#    volumes:
#      - bk4:/var/lib/kafka/data
#      - ./jmx:/opt/jmx_prometheus
#      - ./secrets:/etc/kafka/secrets
#    environment:
#      CLUSTER_ID: "0000000000000000000000"
#      KAFKA_NODE_ID: 4
#      KAFKA_PROCESS_ROLES: broker
#      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:SASL_PLAINTEXT,INTERNAL:SASL_PLAINTEXT,INTERNAL_SSL:SASL_SSL,HOST:SASL_PLAINTEXT,HOST_SSL:SASL_SSL
#      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker-4:9092,INTERNAL_SSL://broker-4:9093,HOST://localhost:49092,HOST_SSL://localhost:49093
#      KAFKA_CONTROLLER_QUORUM_VOTERS: 10@controller-0:9091
#      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
#      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
#      KAFKA_MIN_INSYNC_REPLICAS: 2
#      KAFKA_NUM_PARTITIONS: 4
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
#      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 500
#      KAFKA_METRIC_REPORTERS:
#      KAFKA_OPTS: >-
#        -Djava.security.auth.login.config=/etc/kafka/secrets/broker_jaas.conf
#        -javaagent:/opt/jmx_prometheus/jmx_prometheus_javaagent.jar=7071:/opt/jmx_prometheus/kafka-config.yml
#        -javaagent:/opt/jmx_prometheus/jolokia-jvm.jar=port=7072,host=*
#      CONFLUENT_METRICS_ENABLE: "false"
#      KAFKA_SSL_KEYSTORE_FILENAME: broker-4.keystore.jks
#      KAFKA_SSL_KEYSTORE_CREDENTIALS: kafka.key
#      KAFKA_SSL_KEY_CREDENTIALS: kafka.key
#      KAFKA_SSL_CLIENT_AUTH: none
#      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: kafka.key
#      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.server.truststore.jks
#      KAFKA_AUTHORIZER_CLASS_NAME: org.apache.kafka.metadata.authorizer.StandardAuthorizer
#      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "false"
#      KAFKA_SUPER_USERS: User:kafka-admin;User:kafka-broker;User:kafka-broker-v2
#      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN,SCRAM-SHA-512
#      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
#      KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL: PLAIN

  schema-registry:
    image: confluentinc/cp-schema-registry:${VERSION}
    hostname: schema-registry
    container_name: dk-schema-registry
    stop_grace_period: 60s
    healthcheck:
      test: curl --fail http://localhost:8081/ || exit 1
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 3
    depends_on:
      controller-0:
        condition: service_healthy
      broker-1:
        condition: service_healthy
      broker-2:
        condition: service_healthy
      broker-3:
        condition: service_healthy
    ports:
      - "8081:8081"
    volumes:
      - sr_secrets:/etc/schema-registry/secrets
      - ./jmx:/opt/jmx_prometheus
      - ./secrets:/etc/kafka/secrets
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: broker-1:9092,broker-2:9092,broker-3:9092
      SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: SASL_PLAINTEXT
      SCHEMA_REGISTRY_KAFKASTORE_SASL_MECHANISM: PLAIN
      SCHEMA_REGISTRY_KAFKASTORE_SASL_JAAS_CONFIG: |
        org.apache.kafka.common.security.plain.PlainLoginModule required \
        username="kafka-admin" \
        password="kafka-admin-secret";
      KAFKA_METRIC_REPORTERS:
      CONFLUENT_METRICS_ENABLE: "false"
      EXTRA_OPTS: -javaagent:/opt/jmx_prometheus/jmx_prometheus_javaagent.jar=7071:/opt/jmx_prometheus/sr-config.yml
      SCHEMA_REGISTRY_OPTS: -javaagent:/opt/jmx_prometheus/jmx_prometheus_javaagent.jar=7071:/opt/jmx_prometheus/sr-config.yml

      SCHEMA_REGISTRY_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/schema-registry.keystore.jks
      SCHEMA_REGISTRY_SSL_KEYSTORE_PASSWORD: broker_secret
      SCHEMA_REGISTRY_SSL_KEY_PASSWORD: broker_secret
      SCHEMA_REGISTRY_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/kafka.server.truststore.jks
      SCHEMA_REGISTRY_SSL_TRUSTSTORE_PASSWORD: broker_secret
#not available in schema registry container
#      SCHEMA_REGISTRY_SSL_KEYSTORE_FILENAME: schema-registry.keystore.jks
#      SCHEMA_REGISTRY_SSL_KEYSTORE_CREDENTIALS: kafka.key
#      SCHEMA_REGISTRY_SSL_KEY_CREDENTIALS: kafka.key
#      SCHEMA_REGISTRY_SSL_TRUSTSTORE_CREDENTIALS: kafka.key
#      SCHEMA_REGISTRY_SSL_TRUSTSTORE_FILENAME: kafka.server.truststore.jks

      SCHEMA_REGISTRY_LISTENERS: https://0.0.0.0:8081
      SCHEMA_REGISTRY_INTER_INSTANCE_PROTOCOL: https
#      SCHEMA_REGISTRY_AUTHENTICATION_METHOD: "BASIC"
#      SCHEMA_REGISTRY_AUTHENTICATION_ROLES: "write,read,admin"
#      SCHEMA_REGISTRY_AUTHENTICATION_REALM: "SchemaRegistry"
#      SCHEMA_REGISTRY_OPTS: >-
#        -Djava.security.auth.login.config=/etc/kafka/secrets/sr_jaas.conf

  connect-1:
    image: confluentinc/cp-kafka-connect:${VERSION}
    hostname: connect-1
    container_name: dk-connect-1
    ports:
      - "8083:8083"
    healthcheck:
      test: curl --fail http://localhost:8083/connector-plugins || exit 1
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 15s
    depends_on:
      broker-1:
        condition: service_healthy
    volumes:
      - c_kafka_data:/var/lib/kafka/data
      - c_kafka_secrets:/etc/kafka/secrets
      - ./connect/secrets:/etc/kafka-connect/secrets
      - ./connect/data:/data
      - ./connect/plugins:/etc/kafka-connect/jars
    environment:
      CONNECT_BOOTSTRAP_SERVERS: broker-1:9092,broker-2:9092,broker-3:9092
      CONNECT_SECURITY_PROTOCOL: SASL_PLAINTEXT
      CONNECT_SASL_MECHANISM: PLAIN
      CONNECT_SASL_JAAS_CONFIG: |
        org.apache.kafka.common.security.plain.PlainLoginModule required \
        username="kafka-admin" \
        password="kafka-admin-secret";
      CONNECT_CONNECTOR_CLIENT_CONFIG_OVERRIDE_POLICY: All
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: "connect-cluster"
      CONNECT_CONFIG_STORAGE_TOPIC: "connect-cluster-config"
      CONNECT_OFFSET_STORAGE_TOPIC: "connect-cluster-offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "connect-cluster-status"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 3
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 3
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 3
      CONNECT_CONFIG_PROVIDERS: file
      CONNECT_CONFIG_PROVIDERS_FILE_CLASS: "org.apache.kafka.common.config.provider.FileConfigProvider"
      CONNECT_KEY_CONVERTER: "io.confluent.connect.avro.AvroConverter"
      CONNECT_VALUE_CONVERTER: "io.confluent.connect.avro.AvroConverter"
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_REST_ADVERTISED_HOST_NAME: "connect-1"
      CONNECT_PLUGIN_PATH: /etc/kafka-connect/jars
      CONNECT_LOG4J_ROOT_LOGLEVEL: INFO
      KAFKA_OPTS:
