apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: controller
  namespace: apps
spec:
  serviceName: "kafka-headless"
  replicas: 1
  selector:
    matchLabels:
      app: kafka
      role: controller
  template:
    metadata:
      labels:
        app: kafka
        role: controller
    spec:
#      initContainers:
#        - name: wait-for-broker
#          image: busybox
#          command: ['sh', '-c', 'until nslookup schema-registry.kafka-headless.apps.svc.cluster.local; do echo waiting for connect; sleep 1; done']
      terminationGracePeriodSeconds: 10
      containers:
        - name: kafka
          image: apache/kafka-native:3.8.0
          ports:
            - containerPort: 9092
              name: kafka
            - containerPort: 9093
              name: controller
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: CLUSTER_ID
              value: "0000000000000000000000"
            - name: KAFKA_PROCESS_ROLES
              value: "controller"
            - name: KAFKA_NODE_ID
              value: "10"
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "10@$(HOSTNAME).kafka-headless.apps.svc.cluster.local:9093"
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: CONTROLLER
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
            - name: KAFKA_LISTENERS
              value: CONTROLLER://:9093
            - name: KAFKA_LOG_DIRS
              value: "/opt/kafka/data"
          volumeMounts:
            - name: kafka-storage
              mountPath: /opt/kafka/data
  volumeClaimTemplates:
    - metadata:
        name: kafka-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi  # Adjust storage as needed
