apiVersion: v1
kind: Service
metadata:
  name: schema-registry
  namespace: apps
  labels:
    app: schema-registry
spec:
  selector:
    app: schema-registry
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  clusterIP: None