apiVersion: v1
kind: Service
metadata:
  name: connect
  namespace: apps
  labels:
    app: connect
spec:
  selector:
    app: connect
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  clusterIP: None