apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: apps
type: Opaque
data:
  username: YWRtaW4=  # Base64 encoded 'admin'
  password: cG9zdGdyZXM=  # Base64 encoded 'postgres'
